project_id = "pnnckeqrzjglcwkyzzxg"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.generate-final-offer]
verify_jwt = false

[functions.get-final-offer-url]
verify_jwt = false

[functions.send-quote]
verify_jwt = false

[functions.accept-quote]
verify_jwt = false

[functions.decline-quote]
verify_jwt = false

[functions.ozow-webhook]
verify_jwt = false

[functions.generate-order-confirmation]
verify_jwt = false

[functions.get-order-pdf-url]
verify_jwt = false

[functions.analyse-quote]
verify_jwt = false
