project_id = "pnnckeqrzjglcwkyzzxg"

[functions.trigger-vendor-payout]
verify_jwt = false

[functions.seed-demo-users]
verify_jwt = false

[functions.release-escrow]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.send-waitlist-launch-emails]
verify_jwt = false
