// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";
var projectRef = "pnnckeqrzjglcwkyzzxg";
var mcp_default = defineMcp({
  name: "umcimbi-mcp",
  title: "UMCIMBI",
  version: "0.1.0",
  instructions: "Tools for UMCIMBI, a South African traditional ceremony planning platform. Use `whoami` to confirm identity, `list_my_events` and `list_my_bookings` to read the signed-in planner's ceremonies and vendor bookings, and `search_vendors` to browse the public vendor marketplace by category or free text.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: []
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
