DROP VIEW public.vendors_marketplace;

CREATE VIEW public.vendors_marketplace
WITH (security_invoker = on) AS
SELECT
  id,
  owner_user_id,
  name,
  category,
  location,
  about,
  price_range_text,
  whatsapp_number,
  phone_number,
  email,
  website_url,
  languages,
  rating,
  review_count,
  view_count,
  added_to_events_count,
  is_active,
  image_urls,
  created_at,
  updated_at,
  latitude,
  longitude,
  address_line_1,
  address_line_2,
  city,
  state_province,
  country,
  postal_code,
  vendor_business_type,
  business_verification_status,
  registered_business_name,
  is_super_vendor,
  super_vendor_awarded_at,
  super_vendor_reason,
  verification_reviewed_at,
  verification_reviewed_by,
  logo_url,
  show_registration_on_pdf,
  show_vat_on_pdf,
  letterhead_enabled,
  jobs_completed,
  signup_source,
  payout_method,
  bank_name,
  instagram_url,
  tiktok_url,
  facebook_url,
  is_demo,
  trust_score,
  trust_score_breakdown,
  vendor_tier,
  vendor_tier_override,
  avg_response_time_minutes,
  trust_score_calculated_at,
  is_banned,
  selfie_request_sent_at,
  dormant_nudge_count,
  last_nudge_sent_at,
  last_notified_at
FROM public.vendors;

COMMENT ON VIEW public.vendors_marketplace IS
  'Curated, security_invoker view of public.vendors for signed-in browsing. Excludes bank_account_number, bank_account_holder_name, bank_branch_code, bank_account_type, registration_number, vat_number, admin_approval_notes, selfie_photo_url. Columns are listed explicitly so new vendor columns are never exposed automatically. Read-only: all writes must target public.vendors.';

REVOKE ALL ON public.vendors_marketplace FROM anon;
GRANT SELECT ON public.vendors_marketplace TO authenticated;